# Generated by Django 4.2.5 on 2023-10-22 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('embed_code', models.CharField(max_length=100)),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
    ]
